### ISSUE TITLE
Class Redundancy

### ISSUE THREAD

**Issue by pqt** [seahorsepip/jPopup#1]
I was taking a look over the included css file and I noticed a few class redundancies.

https://github.com/seahorsepip/jPopup/blob/master/css/jpopup.css#L224-L227

**Comment by pqt** [comment]
This will be fixed when https://github.com/seahorsepip/jPopup/pull/2 is merged.

**Comment by AustinPaquette** [comment]
I was curious why this was re-opened all of a sudden, had me worried :worried: @seahorsepip

**Comment by seahorsepip** [comment]
@AustinPaquette Made a mistake xD
Fixing scrollBottom and Overflow issues currently.
