### ISSUE TITLE
Applied overlay z-index too low

### ISSUE THREAD

**Issue by pqt** [seahorsepip/jPopup#3]
I think the z-index should be ~1500 to start off. [The one in bootstrap is 1040.](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L436)

I have a z-index of 180 on a relatively positioned navigation bar (becomes fixed with 200 z-index later on) and it overlays the background.

![](https://i.imgur.com/fZ3tbSX.png)

It doesn't necessarily need to be that high, but 0 is most likely insufficient in a lot of cases.

![](https://i.imgur.com/tFooCQD.png)

With 1500 it does as expected (although it may be a little large of a number respectively)

**Comment by seahorsepip** [comment]
Strange, z-index should start at 1000 by default. I'll look into it.

**Comment by seahorsepip** [comment]
*start at 10000

**Comment by seahorsepip** [comment]
I think it might be a bug I introduced after changing show() into fadeIn() at setOverlay() in the last update. Probably removed the z-index code by accident.

**Comment by seahorsepip** [comment]
Issue has been resolved with last update.

**Comment by pqt** [comment]
@seahorsepip when you commit and it fixes an issue you can add "closes #3" to the commit message (or title) and it will automatically close this.

**Comment by seahorsepip** [comment]
Ah great, learned something new today :smile:
