### ISSUE TITLE
HTML Style

### ISSUE THREAD

**Issue by pqt** [seahorsepip/jPopup#4]
When the popup is activated it currently adds the styling

```
position: fixed;
top: 0px;
width: 100%;
height: 100%;
```

on the HTML tag. This causes you to shoot back up to the top of the page.

I'd like to propose simply adding:

```
overflow: hidden;
```

to avoid this. May not be completely straightforward thought as I haven't tested this theory but I do something similar with mobile navigation on my personal site.

**Comment by seahorsepip** [comment]
overflow: hidden isn't gonna work. (hides scrollbar too which makes the page jump horizontally)
It should not add top: 0px but top: -scrolltop px; so it doesn't jump. can you post and example where it jumps?

**Comment by pqt** [comment]
> (hides scrollbar too which makes the page jump horizontally)

Bootstrap adds a `padding-right: 17px;` If I remember correctly to counter this on Modals.

**Comment by pqt** [comment]
Took a look on their docs example but I don't see it applying a padding-right. Now I'm curious, might dive into this a little more once I get home.

**Comment by seahorsepip** [comment]
padding right wouldn't make sense, every scrollbar width is different. Can you post sent a link with the page jumping? It might just be a matter of adding a scrollFreezeElement option to freeze body instead of html scrolling.

**Comment by pqt** [comment]
As per the second part of [this](http://stackoverflow.com/a/24727026). Should be able to add this to counter that effect.

``` css
body {
    // STOP MOVING AROUND!
    overflow-x: hidden;
    overflow-y: scroll !important;
}
```

(Was looking at a completely different issue but found this applicable)

**Comment by seahorsepip** [comment]
That code doesn't work properly. It moves the page around when it has no scroll bar by adding a scrollbar.

I already fixed the issue, my code works but I needed to replace $("html").scrollTop with $("html, body").scrollTop so it checks for a scrollTop on both the html and body. Almost finished with rewriting the animations, I'll see if I can post an update tomorrow.

**Comment by pqt** [comment]
Did anything ever come of this @seahorsepip ?

I'm keen to include this into a UI kit that I'm building but this is one of the things preventing me from committing to using it.

**Comment by seahorsepip** [comment]
@AustinPaquette
I'll add an update later today that resolves the issue and adds multiple new features.

**Comment by pqt** [comment]
I look forward to it!

**Comment by pqt** [comment]
What was the resolution for it anyhow?

**Comment by seahorsepip** [comment]
@AustinPaquette 

`$("html, body").scrollTop`instead of  `$("html").scrollTop`

and

```
if(window.innerWidth > $("html").width()) {
    $("html").css("overflow-y", "scroll");
}
```

on freeze()

**Comment by seahorsepip** [comment]
Haven't had time to work on this project for a while but I ended up needing it for a project so I finished the code that was WIP and posted an update.
